{
 "title": "exporter",
 "time": { "from": "2024-12-09T15:40:37.846Z", "to": "2024-12-09T16:10:37.846Z" },
 "panels": [
  {
   "title": "Нагрузка на ядра",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage{job=\"exporter\"}",
     "legendFormat": "{{core}} Ядро"
    }
   ]
  },
  {
   "title": "Оперативная память",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "memory_total{job=\"exporter\"} / 1024 / 1024 / 1024",
     "legendFormat": "Всего память"
    },
    {
     "expr": "memory_used{job=\"exporter\"} / 1024 / 1024 / 1024",
     "legendFormat": "Используемая"
    }
   ]
  },
  {
   "title": "Используемая оперативная память",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(memory_used{job=\"exporter\"} / memory_total{job=\"exporter\"}) * 100",
     "legendFormat": "memory_total"
    }
   ]
  },
  {
   "title": "Используемое место на диске",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(disk_used{job=\"exporter\"} / disk_total{job=\"exporter\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}